### PR TITLE
Price

### PR DESCRIPTION
**Pull request by vertraut**
Полностью готовая секция "услуги и цены"

### CODE REVIEW

**Comment by HHEricFrei** [comment]
Hello 
I saw one of your comments on B8 stack and I'm looking for a solution to adapt this great software to my case:
I use it with a Sony 7R 4 and the sony Remote software. (photography)
I do staking + Shift Multi Shooting 4 images. It's great !
(https://www.youtube.com/watch?v=lwwzM81k5VE&t=50s)

I would like to photoshoot very high def with Shift Multi Shooting 16 frames.
Can you do something so that the 16 also work, for exaemple a pause after each 16 Multishoot of 30 seconds .  The PC needs 30 secondes to load 16 images of 60 megapixels. 

Would it be possible to rectify the code and send me a version for this particular case?

that would be great!


Kind regards Eric

**Comment by HHEricFrei** [comment]
Hello Vertraut
Great !!!
ok for a total of $120 = €110
I can only pay by Paypal. Can you send me a paypal address?
As mentioned above, a pause = 30s must be inserted in the initial programme. 
To clarify my request in my photo process:
Remote sony is on Multi16 frame
1/ on B8Stak: go = FOCUS 1
2/ B8 stack on my camera = photo 1
16 photos at the same time (Multishoot)
3/ the images are loaded on the PC: assembly of the .arq = high def 
**Here I'm need 30 seconds** ... Loading
4/ End of loop: FOCUS 2 and photo n ° 2 
start again and for each focus at the same time 30 seconds to load the 16 images 
OK?
Do you have any questions?
I would like to receive the same .exe file because I'm not a Informaticer.
I have every confidence in you and will of course pay you in advance.
Please plan for me to try it on my computer and maybe tweak a bit more.
Thank you very much.

**Comment by vertraut** [comment]
I got it.

My paypal ***@***.***

**Comment by HHEricFrei** [comment]
I can't read it. 
Do you have a website where I can get your e-mail address and communicate directly with you?

**Comment by HHEricFrei** [comment]
I've got an idea... send me a screen capture

**Comment by HHEricFrei** [comment]
of your mail... OK ?

**Comment by HHEricFrei** [comment]
I can't read it.
My paypal ***@***.***

**Comment by vertraut** [comment]
Did you receive the screenshot?

**Comment by HHEricFrei** [comment]
Capture d’écran 2023-11-24 à 17 38 43

**Comment by HHEricFrei** [comment]
no and you ?

**Comment by HHEricFrei** [comment]
ericjbild

**Comment by HHEricFrei** [comment]
in gmail

**Comment by HHEricFrei** [comment]
ok ?
with com...

**Comment by HHEricFrei** [comment]
understand ?

**Pull request merged**
